### ISSUE TITLE
Translations are not working while throwing error from actions

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-workflows#513] opened 2023-11-09 09:39 UTC
#### Describe the bug / expected behavior
Translations are not working while throwing error from actions

#### What are the steps to reproduce?

1. https://github.com/etn-ccis/blui-react-workflows/blob/5270d35d2f251e3337f92f387a13d2fbf6098702/login-workflow/example/src/actions/AuthUIActions.tsx#L14
2. return true from above function
3. cd login-workflows
4. yarn start:example
5. Enter email id and password and click on Login button
6. See the error thrown in the dialog
7. It has only translation keys

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2023-11-09 at 2 49 30 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/120575281/516871b3-d0a3-4041-b36b-d549e621915d">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment] 2023-11-09 18:06
I think this is a duplicate of #510 

The ErrorManager is currently not translating the error messages at all, even if they are internal defaults or using a key from the translations file.

**Closed** 2023-11-20 17:23 UTC
Labels: bug, user-reported, brightlayer-ui
